version: "3.9"
services:
  db:
    image: postgres:13.5-alpine
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 5s
      timeout: 3s
      retries: 6
    volumes:
      - db-data:/var/lib/postgresql/data

  rtsp:
    image: aler9/rtsp-simple-server
    environment:
      RTSP_API: "yes"
      RTSP_PROTOCOLS: "tcp"
  
  mqtt:
    build: 
      context: ./mosquitto
      args:
        mqtt_username: ${MQTT_USERNAME}
        mqtt_password: ${MQTT_PASSWORD}
    restart: always
    ports:
      - '8883:8883'
    volumes:
      - mqtt-data:/mosquitto/data
    
  app:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:5000"
    environment:
      TZ: $SCHEDULER_TIMEZONE
    volumes:
      - ${PWD}/.env:/app/.env

volumes:
  db-data:
  mqtt-data: