version: "3.9"
services:
  db:
    image: postgis/postgis:13-3.2-alpine
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 5s
      timeout: 3s
      retries: 6
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - '6379:6379'

  mqtt:
    build: 
      context: ./mosquitto
      args:
        mqtt_username: ${MQTT_USERNAME}
        mqtt_password: ${MQTT_PASSWORD}
    restart: always
    ports:
      - '1883:1883'
      - '8883:8883'
    volumes:
      - mqtt-data:/mosquitto/data
    
  app:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:5000"
    environment:
      TZ: $SCHEDULER_TIMEZONE
    volumes:
      - ${PWD}/.env:/app/.env
      - /ramdisks:/app/ramdisks

  worker:
    image: woodcam-rm_app:latest
    restart: always
    command: celery -A woodcamrm.celery worker --loglevel=info
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: $SCHEDULER_TIMEZONE
    volumes:
      - ${PWD}/.env:/app/.env
      - /ramdisks:/app/ramdisks

volumes:
  db-data:
  mqtt-data:
