version: "3.9"
services:
  db:
    image: postgis/postgis:13-3.2-alpine
    environment:
      TZ: $SCHEDULER_TIMEZONE
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 5s
      timeout: 3s
      retries: 6
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-rc2-alpine
    environment:
      TZ: $SCHEDULER_TIMEZONE
      REDIS_PASSWORD: $REDIS_PASSWORD
    command: redis-server --save 20 1 --loglevel warning --stop-writes-on-bgsave-error no --requirepass ${REDIS_PASSWORD}
    
  ftp:
    image: delfer/alpine-ftp-server
    restart: always
    environment:
      TZ: $SCHEDULER_TIMEZONE
      USERS: ${FTP_USER}|${FTP_PASSWORD}|/data
      ADDRESS: ${APP_URL}
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - video-data:/data

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:5000"
    environment:
      TZ: $SCHEDULER_TIMEZONE
    volumes:
      - ./.env:/app/.env
      - video-data:/data
      - ./:/app
      - prometheus-config:/etc/prometheus
      - grafana-config:/etc/grafana
    command: flask run --host=0.0.0.0

  worker:
    image: woodcam-rm_app:latest
    command: celery -A woodcamrm.celery worker --loglevel=debug -c 10
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: $SCHEDULER_TIMEZONE
    volumes:
      - ./.env:/app/.env
      - video-data:/data
      - ./:/app

  prometheus:
    image: prom/prometheus:v2.36.1
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - prometheus-config:/etc/prometheus
      - ./ssl_certs/cert.pem:/etc/prometheus/cert.pem
      - ./ssl_certs/privkey.pem:/etc/prometheus/privkey.pem
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=365d'  
      - '--web.config.file=/etc/prometheus/web.yml'

  alertmanager:
    image: prom/alertmanager:v0.24.0
    volumes:
      - prometheus-config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/alertmanager.yml'
    ports:
      - 9093:9093

  psql-exporter:
    image: prometheuscommunity/postgres-exporter:v0.10.1
    environment:
      DATA_SOURCE_NAME: ${SQLALCHEMY_DATABASE_URI}?sslmode=disable
    volumes:
      - prometheus-config:/etc/prometheus
    command:
      - '--extend.query-path=/etc/prometheus/queries.yaml'
    ports:
      - 9187:9187

  snmp-exporter:
    image: prom/snmp-exporter:v0.20.0
    volumes:
      - prometheus-config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/snmp.yml'
    ports:
      - 9116:9116

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.21.1
    volumes:
      - prometheus-config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/blackbox.yml'
    ports:
      - 9115:9115

  grafana:
    image: grafana/grafana-oss
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
      - ./ssl_certs/cert.pem:/etc/grafana/cert.pem
      - ./ssl_certs/privkey.pem:/etc/grafana/privkey.pem
    environment:
      GF_SECURITY_ADMIN_USER: ${DEFAULT_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${DEFAULT_PASSWORD}
      GF_SMTP_ENABLED: 'true'
      GF_SMTP_HOST: ${MAIL_SERVER}
      GF_SMTP_USER: ${MAIL_USERNAME}
      GF_SMTP_PASSWORD: ${MAIL_PASSWORD}
      GF_SMTP_FROM_ADDRESS: ${MAIL_DEFAULT_SENDER}
      GF_SERVER_CERT_FILE: /etc/grafana/cert.pem
      GF_SERVER_CERT_KEY: /etc/grafana/privkey.pem
    ports:
      - 3000:3000

volumes:
  db-data:
  prometheus-data:
  prometheus-config:
  grafana-data:
  grafana-config:
  video-data:
    driver_opts:
     type: tmpfs
     device: tmpfs
