pg_woodcamrm_stations:
  master: true
  query: "SELECT common_name, water_level, last_hydro, current_data, ping_alert, current_daymode, current_recording, monthly_data FROM stations"
  metrics:
    - common_name:
        usage: "LABEL"
        description: "Station full name"
    - water_level:
        usage: "GAUGE"
        decription: "Station video water level"
    - last_hydro:
        usage: "GAUGE"
        decription: "Station API water level"
    - current_daymode:
        usage: "GAUGE"
        description: "Current night/day mode"
    - current_recording:
        usage: "GAUGE"
        description: "Current recording mode"
    - monthly_data:
        usage: "GAUGE"
        description: "Monthly data included in telecom provider plan"

pg_woodcamrm_jobs:
  master: true
  query: "SELECT job_name, state FROM jobs"
  metrics:
    - job_name:
        usage: "LABEL"
        description: "Job identifier"
    - state:
        usage: "GAUGE"
        description: "Job state"
