"""add snmp monitoring field

Revision ID: 02bcb19d5360
Revises: 3622cbd7c18e
Create Date: 2022-06-29 10:31:37.459809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02bcb19d5360'
down_revision = '3622cbd7c18e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('snmp_monitoring', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE stations SET snmp_monitoring = false")
    op.alter_column('stations', 'snmp_monitoring', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'snmp_monitoring')
    # ### end Alembic commands ###
