"""create planned recoveries table

Revision ID: 251ffeecab94
Revises: a17e2ea61402
Create Date: 2022-10-26 12:42:13.485167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251ffeecab94'
down_revision = 'a17e2ea61402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planned_recoveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=120), nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=False),
    sa.Column('to_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planned_recoveries')
    # ### end Alembic commands ###
