"""recording mode recreate column

Revision ID: 3622cbd7c18e
Revises: bbe0a6366886
Create Date: 2022-06-20 14:25:11.224489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3622cbd7c18e'
down_revision = 'bbe0a6366886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('current_recording', sa.Integer(), nullable=False, default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'current_recording')
    # ### end Alembic commands ###
