"""initial migration

Revision ID: 463c0f11163f
Revises: 
Create Date: 2022-04-29 14:34:25.398572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463c0f11163f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('last_execution', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Enum('running', 'warn', 'error', 'stopped', name='jobstate'), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parameter')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=120), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('api_name', sa.String(length=120), nullable=True),
    sa.Column('long', sa.Numeric(), nullable=True),
    sa.Column('lat', sa.Numeric(), nullable=True),
    sa.Column('phone_number', sa.String(length=120), nullable=True),
    sa.Column('monthly_data', sa.Integer(), nullable=True),
    sa.Column('current_data', sa.Numeric(), nullable=True),
    sa.Column('last_data_check', sa.DateTime(), nullable=True),
    sa.Column('reset_day', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=120), nullable=True),
    sa.Column('camera_port', sa.Integer(), nullable=True),
    sa.Column('installation_port', sa.Integer(), nullable=True),
    sa.Column('mqtt_prefix', sa.String(length=120), nullable=True),
    sa.Column('snmp_received', sa.String(length=120), nullable=True),
    sa.Column('snmp_transmitted', sa.String(length=120), nullable=True),
    sa.Column('last_ping', sa.DateTime(), nullable=True),
    sa.Column('ping_alert', sa.Boolean(), nullable=False),
    sa.Column('last_hydro_time', sa.DateTime(), nullable=True),
    sa.Column('last_hydro', sa.Numeric(), nullable=True),
    sa.Column('water_level', sa.Numeric(), nullable=True),
    sa.Column('current_recording', sa.Enum('high', 'low', 'no', name='recordmode'), nullable=True),
    sa.Column('last_record_change', sa.DateTime(), nullable=True),
    sa.Column('storage_path', sa.String(length=120), nullable=True),
    sa.Column('current_daymode', sa.Integer(), nullable=True),
    sa.Column('temp_alert', sa.Integer(), nullable=False),
    sa.Column('sd_alert', sa.Integer(), nullable=False),
    sa.Column('sd_disruption', sa.Integer(), nullable=False),
    sa.Column('tampering', sa.Integer(), nullable=False),
    sa.Column('rtsp_url', sa.String(length=120), nullable=True),
    sa.Column('jan_threshold', sa.Numeric(), nullable=True),
    sa.Column('feb_threshold', sa.Numeric(), nullable=True),
    sa.Column('mar_threshold', sa.Numeric(), nullable=True),
    sa.Column('apr_threshold', sa.Numeric(), nullable=True),
    sa.Column('may_threshold', sa.Numeric(), nullable=True),
    sa.Column('jun_threshold', sa.Numeric(), nullable=True),
    sa.Column('jul_threshold', sa.Numeric(), nullable=True),
    sa.Column('aug_threshold', sa.Numeric(), nullable=True),
    sa.Column('sep_threshold', sa.Numeric(), nullable=True),
    sa.Column('oct_threshold', sa.Numeric(), nullable=True),
    sa.Column('nov_threshold', sa.Numeric(), nullable=True),
    sa.Column('dec_threshold', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('common_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'viewer', name='role'), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('stations')
    op.drop_table('settings')
    op.drop_table('jobs')
    # ### end Alembic commands ###
