"""initial migration

Revision ID: 6d037e99c04d
Revises: 
Create Date: 2022-04-26 13:25:12.988954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d037e99c04d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stations_geom', table_name='stations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_stations_geom', 'stations', ['geom'], unique=False)
    # ### end Alembic commands ###
