"""job status recreate

Revision ID: 8692889ba8fa
Revises: b66ba8bd6188
Create Date: 2022-06-20 14:07:14.456793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8692889ba8fa'
down_revision = 'b66ba8bd6188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('state', sa.Integer(), nullable=True, default=1))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'state')
    # ### end Alembic commands ###
