"""add camera api auth data

Revision ID: a17e2ea61402
Revises: 02bcb19d5360
Create Date: 2022-10-25 17:18:51.948968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17e2ea61402'
down_revision = '02bcb19d5360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('api_user', sa.String(length=120), nullable=True))
    op.add_column('stations', sa.Column('api_password', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'api_password')
    op.drop_column('stations', 'api_user')
    # ### end Alembic commands ###
