"""add last_data value

Revision ID: af237982ccc7
Revises: 463c0f11163f
Create Date: 2022-06-14 16:18:52.527245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af237982ccc7'
down_revision = '463c0f11163f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('last_data', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'last_data')
    # ### end Alembic commands ###
