"""job status drop

Revision ID: b66ba8bd6188
Revises: 87de15463d1e
Create Date: 2022-06-20 14:03:31.668793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b66ba8bd6188'
down_revision = '87de15463d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('state', postgresql.ENUM('running', 'warn', 'error', 'stopped', name='jobstate'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
