"""recording mode drop column

Revision ID: bbe0a6366886
Revises: 8692889ba8fa
Create Date: 2022-06-20 14:24:27.747276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbe0a6366886'
down_revision = '8692889ba8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'current_recording')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('current_recording', postgresql.ENUM('high', 'low', 'no', name='recordmode'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
