{
 "title": "WoodCam RM main dashboard",
 "tags": [ "woodcam-rm" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "station", "label": "Station", "query": { "query": "label_values(common_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Mobile signal stregth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "signalStrength{job=\"geneko_snmp\"}",
     "legendFormat": "{{common_name}}"
    }
   ]
  },
  {
   "title": "Installation status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "probe_success{common_name=~\"$station\", hardware=\"router\"}",
     "legendFormat": "{{common_name}}"
    }
   ]
  },
  {
   "title": "Data transmitted 31 rolling days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (common_name) (increase(dataTransmitted[31d])+increase(dataReceived[31d]))",
     "legendFormat": "{{common_name}}"
    }
   ]
  },
  {
   "title": "Jobs status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "pg_woodcamrm_jobs_state", "legendFormat": "{{job_name}}" }
   ]
  },
  {
   "title": "API water level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "pg_woodcamrm_stations_last_hydro{common_name=~\"$station\"}",
     "legendFormat": "{{common_name}}"
    }
   ]
  },
  {
   "title": "Recording mode",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "pg_woodcamrm_stations_current_recording{common_name=~\"$station\"}",
     "legendFormat": "{{common_name}}"
    }
   ]
  },
  {
   "title": "Day/Night mode",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "pg_woodcamrm_stations_current_daymode{common_name=~\"$station\"}",
     "legendFormat": "{{common_name}}"
    }
   ]
  }
 ]
}